server:
  port: 7001

logging:
  config: classpath:logback-spring.xml
  path: /home/ap/nas_a/logback/logs/spring-boot-demo-logback.log

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:7000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS




